language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t choi205/react-test-app -f ./frontend/Docker.dev ./frontend

script:
    - docker run -e CI=true choi205/reqct-test-app npm run test

after_success:
    - docker build -t choi205/docker-frontend ./frontend
    - docker build -t choi205/docker-backend ./backend
    - docker build -t choi205/docker-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

    - docker push choi205/docker-frontend
    - docker push choi205/docker-backend
    - docker push choi205/docker-nginx