language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t chlwnsgur205/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true chlwnsgur205/react-test-app npm run test

after_success:
    - docker build -t chlwnsgur205/docker-frontend ./frontend
    - docker build -t chlwnsgur205/docker-backend ./backend
    - docker build -t chlwnsgur205/docker-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

    - docker push chlwnsgur205/docker-frontend
    - docker push chlwnsgur205/docker-backend
    - docker push chlwnsgur205/docker-nginx

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker-fullstack-app"
    env: "DockerFullstackApp-env"
    bucket_name: elasticbeanstalk-ap-northeast-2-175857302356
    bucket_path: "docker-fullstack-app"
    on:
        branch: master
    
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY